/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seleuco_mame4droid_Emulator */

#ifndef _Included_com_seleuco_mame4droid_Emulator
#define _Included_com_seleuco_mame4droid_Emulator
#ifdef __cplusplus
extern "C" {
#endif
#undef com_seleuco_mame4droid_Emulator_IN_MENU
#define com_seleuco_mame4droid_Emulator_IN_MENU 1L
#undef com_seleuco_mame4droid_Emulator_IN_GAME
#define com_seleuco_mame4droid_Emulator_IN_GAME 2L
#undef com_seleuco_mame4droid_Emulator_NUMBTNS
#define com_seleuco_mame4droid_Emulator_NUMBTNS 3L
#undef com_seleuco_mame4droid_Emulator_NUMWAYS
#define com_seleuco_mame4droid_Emulator_NUMWAYS 4L
#undef com_seleuco_mame4droid_Emulator_IS_LIGHTGUN
#define com_seleuco_mame4droid_Emulator_IS_LIGHTGUN 5L
#undef com_seleuco_mame4droid_Emulator_EXIT_GAME
#define com_seleuco_mame4droid_Emulator_EXIT_GAME 1L
#undef com_seleuco_mame4droid_Emulator_EXIT_PAUSE
#define com_seleuco_mame4droid_Emulator_EXIT_PAUSE 2L
#undef com_seleuco_mame4droid_Emulator_SHOW_FPS
#define com_seleuco_mame4droid_Emulator_SHOW_FPS 3L
#undef com_seleuco_mame4droid_Emulator_AUTO_FRAMESKIP
#define com_seleuco_mame4droid_Emulator_AUTO_FRAMESKIP 4L
#undef com_seleuco_mame4droid_Emulator_CHEATS
#define com_seleuco_mame4droid_Emulator_CHEATS 5L
#undef com_seleuco_mame4droid_Emulator_SKIP_GAMEINFO
#define com_seleuco_mame4droid_Emulator_SKIP_GAMEINFO 6L
#undef com_seleuco_mame4droid_Emulator_DISABLE_DRC
#define com_seleuco_mame4droid_Emulator_DISABLE_DRC 7L
#undef com_seleuco_mame4droid_Emulator_DRC_USE_C
#define com_seleuco_mame4droid_Emulator_DRC_USE_C 8L
#undef com_seleuco_mame4droid_Emulator_SIMPLE_UI
#define com_seleuco_mame4droid_Emulator_SIMPLE_UI 9L
#undef com_seleuco_mame4droid_Emulator_PAUSE
#define com_seleuco_mame4droid_Emulator_PAUSE 11L
#undef com_seleuco_mame4droid_Emulator_SOUND_VALUE
#define com_seleuco_mame4droid_Emulator_SOUND_VALUE 13L
#undef com_seleuco_mame4droid_Emulator_AUTOSAVE
#define com_seleuco_mame4droid_Emulator_AUTOSAVE 16L
#undef com_seleuco_mame4droid_Emulator_SAVESTATE
#define com_seleuco_mame4droid_Emulator_SAVESTATE 17L
#undef com_seleuco_mame4droid_Emulator_LOADSTATE
#define com_seleuco_mame4droid_Emulator_LOADSTATE 18L
#undef com_seleuco_mame4droid_Emulator_OSD_RESOLUTION
#define com_seleuco_mame4droid_Emulator_OSD_RESOLUTION 20L
#undef com_seleuco_mame4droid_Emulator_EMU_RESOLUTION
#define com_seleuco_mame4droid_Emulator_EMU_RESOLUTION 21L
#undef com_seleuco_mame4droid_Emulator_ZOOM_TO_WINDOW
#define com_seleuco_mame4droid_Emulator_ZOOM_TO_WINDOW 22L
#undef com_seleuco_mame4droid_Emulator_DOUBLE_BUFFER
#define com_seleuco_mame4droid_Emulator_DOUBLE_BUFFER 23L
#undef com_seleuco_mame4droid_Emulator_PXASP1
#define com_seleuco_mame4droid_Emulator_PXASP1 24L
#undef com_seleuco_mame4droid_Emulator_VBEAM2X
#define com_seleuco_mame4droid_Emulator_VBEAM2X 34L
#undef com_seleuco_mame4droid_Emulator_VFLICKER
#define com_seleuco_mame4droid_Emulator_VFLICKER 36L
#undef com_seleuco_mame4droid_Emulator_SOUND_OPTIMAL_FRAMES
#define com_seleuco_mame4droid_Emulator_SOUND_OPTIMAL_FRAMES 48L
#undef com_seleuco_mame4droid_Emulator_SOUND_OPTIMAL_SAMPLERATE
#define com_seleuco_mame4droid_Emulator_SOUND_OPTIMAL_SAMPLERATE 49L
#undef com_seleuco_mame4droid_Emulator_SOUND_ENGINE
#define com_seleuco_mame4droid_Emulator_SOUND_ENGINE 50L
#undef com_seleuco_mame4droid_Emulator_MOUSE
#define com_seleuco_mame4droid_Emulator_MOUSE 60L
#undef com_seleuco_mame4droid_Emulator_REFRESH
#define com_seleuco_mame4droid_Emulator_REFRESH 61L
#undef com_seleuco_mame4droid_Emulator_USING_SAF
#define com_seleuco_mame4droid_Emulator_USING_SAF 62L
#undef com_seleuco_mame4droid_Emulator_SAVESATES_IN_ROM_PATH
#define com_seleuco_mame4droid_Emulator_SAVESATES_IN_ROM_PATH 63L
#undef com_seleuco_mame4droid_Emulator_WARN_ON_EXIT
#define com_seleuco_mame4droid_Emulator_WARN_ON_EXIT 64L
#undef com_seleuco_mame4droid_Emulator_IS_MOUSE
#define com_seleuco_mame4droid_Emulator_IS_MOUSE 65L
#undef com_seleuco_mame4droid_Emulator_KEYBOARD
#define com_seleuco_mame4droid_Emulator_KEYBOARD 66L
#undef com_seleuco_mame4droid_Emulator_ONE_PROCESSOR
#define com_seleuco_mame4droid_Emulator_ONE_PROCESSOR 67L
#undef com_seleuco_mame4droid_Emulator_NODEADZONEANDSAT
#define com_seleuco_mame4droid_Emulator_NODEADZONEANDSAT 68L
#undef com_seleuco_mame4droid_Emulator_MAMEINI
#define com_seleuco_mame4droid_Emulator_MAMEINI 69L
#undef com_seleuco_mame4droid_Emulator_SPEED_HACKS
#define com_seleuco_mame4droid_Emulator_SPEED_HACKS 70L
#undef com_seleuco_mame4droid_Emulator_AUTOFIRE
#define com_seleuco_mame4droid_Emulator_AUTOFIRE 71L
#undef com_seleuco_mame4droid_Emulator_INPUTMACRO
#define com_seleuco_mame4droid_Emulator_INPUTMACRO 72L
#undef com_seleuco_mame4droid_Emulator_HISCORE
#define com_seleuco_mame4droid_Emulator_HISCORE 73L
#undef com_seleuco_mame4droid_Emulator_SAF_PATH
#define com_seleuco_mame4droid_Emulator_SAF_PATH 1L
#undef com_seleuco_mame4droid_Emulator_ROM_NAME
#define com_seleuco_mame4droid_Emulator_ROM_NAME 2L
#undef com_seleuco_mame4droid_Emulator_VERSION
#define com_seleuco_mame4droid_Emulator_VERSION 3L
#undef com_seleuco_mame4droid_Emulator_OVERLAY_EFECT
#define com_seleuco_mame4droid_Emulator_OVERLAY_EFECT 4L
#undef com_seleuco_mame4droid_Emulator_CLI_PARAMS
#define com_seleuco_mame4droid_Emulator_CLI_PARAMS 5L
#undef com_seleuco_mame4droid_Emulator_MAME_VERSION
#define com_seleuco_mame4droid_Emulator_MAME_VERSION 1L
#undef com_seleuco_mame4droid_Emulator_KEY_DOWN
#define com_seleuco_mame4droid_Emulator_KEY_DOWN 1L
#undef com_seleuco_mame4droid_Emulator_KEY_UP
#define com_seleuco_mame4droid_Emulator_KEY_UP 2L
#undef com_seleuco_mame4droid_Emulator_MOUSE_MOVE
#define com_seleuco_mame4droid_Emulator_MOUSE_MOVE 1L
#undef com_seleuco_mame4droid_Emulator_MOUSE_BTN_DOWN
#define com_seleuco_mame4droid_Emulator_MOUSE_BTN_DOWN 2L
#undef com_seleuco_mame4droid_Emulator_MOUSE_BTN_UP
#define com_seleuco_mame4droid_Emulator_MOUSE_BTN_UP 3L
/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_init
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    runT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_runT
  (JNIEnv *, jclass);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    setDigitalData
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_setDigitalData
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    setAnalogData
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_setAnalogData
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    getValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_seleuco_mame4droid_Emulator_getValue
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    getValueStr
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_seleuco_mame4droid_Emulator_getValueStr
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    setValue
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_setValue
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    setValueStr
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_seleuco_mame4droid_Emulator_setValueStr
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    setKeyData
 * Signature: (IIC)I
 */
JNIEXPORT jint JNICALL Java_com_seleuco_mame4droid_Emulator_setKeyData
  (JNIEnv *, jclass, jint, jint, jchar);

/*
 * Class:     com_seleuco_mame4droid_Emulator
 * Method:    setMouseData
 * Signature: (IIIFF)I
 */
JNIEXPORT jint JNICALL Java_com_seleuco_mame4droid_Emulator_setMouseData
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
